# Site Identity
title: Cybersecurity & AI Strategy
email: cn.research@outlook.com
description: >-
  Strategic insights and implementation frameworks for AI-enhanced cybersecurity operations, from concept to deployment.
github_username: CyberDoc88
minimal_mistakes_skin: air
search: true

# Manual Navigation
# Controlled via _data/navigation.yml

# Theme and Build Settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/Chicago

# Include custom folders
include:
  - _pages
  - _data

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Info
author:
  name   : "C Nott"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Cybersecurity leader and AI strategist | CTI, digital forensics, counterintelligence"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cnott"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:cn.research@outlook.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CyberDoc88"

# Footer Links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cnott"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CyberDoc88"

# Layout Defaults (includes custom head injection)
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      head: head-custom.html

  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# Disable category and tag pages (optional cleanup)
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
