# Site Identity
title: Cybersecurity & AI Strategy
email: cn.research@outlook.com
description: >-
  Strategic insights and implementation frameworks for AI-enhanced cybersecurity operations, from concept to deployment.
github_username: CyberDoc88
minimal_mistakes_skin: default
search: true

# Manual Navigation Bar
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/   # change to /publications/ if not renamed
  - title: "Insights"
    url: /insights/

# Build Settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/Chicago  # optional, adjust as needed

# Include directories
include:
  - _pages

# Plugins (required for full functionality)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Profile
author:
  name   : "C Nott"
  avatar : "/assets/images/bio-photo.jpg"  # Optional: update or remove
  bio    : "Cybersecurity leader and AI strategist | CTI, digital forensics, counterintelligence"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cnott"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:cn.research@outlook.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CyberDoc88"

# Footer (optional, simplified)
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cnott"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CyberDoc88"

# Page Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Disable Categories and Tags Archive Pages
# (They cause empty links if no posts are tagged)
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
